[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db -p no:warnings --strict-markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    kernel_integration: marks tests that explicitly hit the C++ FFI
