import os
import grpc
import logging
from typing import List, Dict

# These modules are generated by grpcio-tools based on the feed.proto file
from kernel.proto import feed_pb2, feed_pb2_grpc

logger = logging.getLogger(__name__)

# Route to the C++ microservice (Docker hostname)
KERNEL_TARGET = os.environ.get('KERNEL_GRPC_TARGET', 'localhost:50051')

def parse_feed_stream(raw_xml_bytes: bytes) -> List[Dict]:
    """
    Acts as the FFI bridge. Pushes raw bytes across the gRPC channel to 
    the C++20 kernel, completely bypassing Python's GIL for string parsing.
    """
    try:
        # In a high-throughput env, the channel should be persistent/cached.
        with grpc.insecure_channel(KERNEL_TARGET) as channel:
            stub = feed_pb2_grpc.SyndicationParserStub(channel)
            request = feed_pb2.RawStreamRequest(payload=raw_xml_bytes)
            
            # 5-second hard timeout for the C++ kernel to respond
            response = stub.ParseStream(request, timeout=5.0)
            
            return [
                {
                    'guid': entry.guid,
                    'title': entry.title,
                    'url': entry.url,
                    'content': entry.content,
                    'published_at': entry.published_at
                }
                for entry in response.entries
            ]
    except grpc.RpcError as e:
        logger.error(f"Kernel parsing failure: {e.details()} (Status: {e.code()})")
        return []
