#pragma once

#include <grpcpp/grpcpp.h>
#include "feed.grpc.pb.h" // Generated by protoc
#include "parser/feed_parser.hpp"
#include "core/safe_buffer.hpp"

namespace simplefeed::server {

    class SyndicationServiceImpl final : public kernel::SyndicationParser::Service {
    public:
        grpc::Status ParseStream(
            grpc::ServerContext* context, 
            const kernel::RawStreamRequest* request, 
            kernel::ParsedStreamResponse* response) override;
    };

} // namespace simplefeed::server
