from django.db import models
from django.db.models import JSONField
from feeds.models import Workspace

class EventManifest(models.Model):
    """
    A one-time configuration payload for an async life event. 
    Acts as the 'Project Charter' for the AI agent.
    """
    id = models.CharField(primary_key=True, max_length=64)
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    
    label = models.CharField(max_length=150)  # e.g., "Tokyo Autumn Trip with Brother"
    destination_code = models.CharField(max_length=10)  # e.g., "HND" or "NRT"
    origin_code = models.CharField(max_length=10) # e.g., "JFK"
    
    # Deterministic Triggers
    target_date_start = models.DateField()
    target_date_end = models.DateField()
    max_flight_price_usd = models.FloatField()
    
    # Agentic Directive (The qualitative instructions)
    ai_reporting_directive = models.TextField(
        help_text="e.g., 'Track the Yen exchange rate and flag any major weather events or festivals.'"
    )
    
    is_active = models.BooleanField(default=True)
    last_briefing_generated = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'plan_event_manifests'


class LogisticsSnapshot(models.Model):
    """Stores the synthesized reports generated by the agent for Notion-style rendering."""
    manifest = models.ForeignKey(EventManifest, on_delete=models.CASCADE, related_name="snapshots")
    timestamp = models.DateTimeField(auto_now_add=True)
    
    lowest_fare_found = models.FloatField()
    fare_metadata = JSONField() # Airlines, layovers, links
    
    ai_synthesized_brief = models.TextField() # The Notion-style markdown report
    trigger_condition_met = models.BooleanField(default=False)
